//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.UI.HRServiceCompanyInsertApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAciklamasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternetSitesiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketUnvaniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SirketAciklamasi {
            get {
                return this.SirketAciklamasiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAciklamasiField, value) != true)) {
                    this.SirketAciklamasiField = value;
                    this.RaisePropertyChanged("SirketAciklamasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InternetSitesi {
            get {
                return this.InternetSitesiField;
            }
            set {
                if ((object.ReferenceEquals(this.InternetSitesiField, value) != true)) {
                    this.InternetSitesiField = value;
                    this.RaisePropertyChanged("InternetSitesi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SirketUnvani {
            get {
                return this.SirketUnvaniField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketUnvaniField, value) != true)) {
                    this.SirketUnvaniField = value;
                    this.RaisePropertyChanged("SirketUnvani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LogoPath {
            get {
                return this.LogoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoPathField, value) != true)) {
                    this.LogoPathField = value;
                    this.RaisePropertyChanged("LogoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HR.UI.HRServiceCompanyInsertApp.ResultOfListOfCompany))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfListOfCompany", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultOfListOfCompany : HR.UI.HRServiceCompanyInsertApp.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HR.UI.HRServiceCompanyInsertApp.Company[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HR.UI.HRServiceCompanyInsertApp.Company[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRServiceCompanyInsertApp.CompanyServicesSoap")]
    public interface CompanyServicesSoap {
        
        // CODEGEN: Generating message contract since element name company from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        HR.UI.HRServiceCompanyInsertApp.InsertResponse Insert(HR.UI.HRServiceCompanyInsertApp.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.InsertResponse> InsertAsync(HR.UI.HRServiceCompanyInsertApp.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        HR.UI.HRServiceCompanyInsertApp.DeleteResponse Delete(HR.UI.HRServiceCompanyInsertApp.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.DeleteResponse> DeleteAsync(HR.UI.HRServiceCompanyInsertApp.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name company from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        HR.UI.HRServiceCompanyInsertApp.UpdateResponse Update(HR.UI.HRServiceCompanyInsertApp.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.UpdateResponse> UpdateAsync(HR.UI.HRServiceCompanyInsertApp.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCompanyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCompany", ReplyAction="*")]
        HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse GetAllCompany(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse> GetAllCompanyAsync(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(HR.UI.HRServiceCompanyInsertApp.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.Company company;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(HR.UI.HRServiceCompanyInsertApp.Company company) {
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(HR.UI.HRServiceCompanyInsertApp.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.Result InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(HR.UI.HRServiceCompanyInsertApp.Result InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(HR.UI.HRServiceCompanyInsertApp.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(HR.UI.HRServiceCompanyInsertApp.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.Result DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(HR.UI.HRServiceCompanyInsertApp.Result DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(HR.UI.HRServiceCompanyInsertApp.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.Company company;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(HR.UI.HRServiceCompanyInsertApp.Company company) {
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(HR.UI.HRServiceCompanyInsertApp.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.Result UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(HR.UI.HRServiceCompanyInsertApp.Result UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCompany", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequestBody Body;
        
        public GetAllCompanyRequest() {
        }
        
        public GetAllCompanyRequest(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCompanyRequestBody {
        
        public GetAllCompanyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCompanyResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponseBody Body;
        
        public GetAllCompanyResponse() {
        }
        
        public GetAllCompanyResponse(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCompanyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceCompanyInsertApp.ResultOfListOfCompany GetAllCompanyResult;
        
        public GetAllCompanyResponseBody() {
        }
        
        public GetAllCompanyResponseBody(HR.UI.HRServiceCompanyInsertApp.ResultOfListOfCompany GetAllCompanyResult) {
            this.GetAllCompanyResult = GetAllCompanyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompanyServicesSoapChannel : HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyServicesSoapClient : System.ServiceModel.ClientBase<HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap>, HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap {
        
        public CompanyServicesSoapClient() {
        }
        
        public CompanyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceCompanyInsertApp.InsertResponse HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.Insert(HR.UI.HRServiceCompanyInsertApp.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public HR.UI.HRServiceCompanyInsertApp.Result Insert(HR.UI.HRServiceCompanyInsertApp.Company company) {
            HR.UI.HRServiceCompanyInsertApp.InsertRequest inValue = new HR.UI.HRServiceCompanyInsertApp.InsertRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.InsertRequestBody();
            inValue.Body.company = company;
            HR.UI.HRServiceCompanyInsertApp.InsertResponse retVal = ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.InsertResponse> HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.InsertAsync(HR.UI.HRServiceCompanyInsertApp.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.InsertResponse> InsertAsync(HR.UI.HRServiceCompanyInsertApp.Company company) {
            HR.UI.HRServiceCompanyInsertApp.InsertRequest inValue = new HR.UI.HRServiceCompanyInsertApp.InsertRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.InsertRequestBody();
            inValue.Body.company = company;
            return ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceCompanyInsertApp.DeleteResponse HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.Delete(HR.UI.HRServiceCompanyInsertApp.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public HR.UI.HRServiceCompanyInsertApp.Result Delete(int id) {
            HR.UI.HRServiceCompanyInsertApp.DeleteRequest inValue = new HR.UI.HRServiceCompanyInsertApp.DeleteRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.DeleteRequestBody();
            inValue.Body.id = id;
            HR.UI.HRServiceCompanyInsertApp.DeleteResponse retVal = ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.DeleteResponse> HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.DeleteAsync(HR.UI.HRServiceCompanyInsertApp.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.DeleteResponse> DeleteAsync(int id) {
            HR.UI.HRServiceCompanyInsertApp.DeleteRequest inValue = new HR.UI.HRServiceCompanyInsertApp.DeleteRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.DeleteRequestBody();
            inValue.Body.id = id;
            return ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceCompanyInsertApp.UpdateResponse HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.Update(HR.UI.HRServiceCompanyInsertApp.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public HR.UI.HRServiceCompanyInsertApp.Result Update(HR.UI.HRServiceCompanyInsertApp.Company company) {
            HR.UI.HRServiceCompanyInsertApp.UpdateRequest inValue = new HR.UI.HRServiceCompanyInsertApp.UpdateRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.UpdateRequestBody();
            inValue.Body.company = company;
            HR.UI.HRServiceCompanyInsertApp.UpdateResponse retVal = ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.UpdateResponse> HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.UpdateAsync(HR.UI.HRServiceCompanyInsertApp.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.UpdateResponse> UpdateAsync(HR.UI.HRServiceCompanyInsertApp.Company company) {
            HR.UI.HRServiceCompanyInsertApp.UpdateRequest inValue = new HR.UI.HRServiceCompanyInsertApp.UpdateRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.UpdateRequestBody();
            inValue.Body.company = company;
            return ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.GetAllCompany(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest request) {
            return base.Channel.GetAllCompany(request);
        }
        
        public HR.UI.HRServiceCompanyInsertApp.ResultOfListOfCompany GetAllCompany() {
            HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest inValue = new HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequestBody();
            HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse retVal = ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).GetAllCompany(inValue);
            return retVal.Body.GetAllCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse> HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap.GetAllCompanyAsync(HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest request) {
            return base.Channel.GetAllCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceCompanyInsertApp.GetAllCompanyResponse> GetAllCompanyAsync() {
            HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest inValue = new HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequest();
            inValue.Body = new HR.UI.HRServiceCompanyInsertApp.GetAllCompanyRequestBody();
            return ((HR.UI.HRServiceCompanyInsertApp.CompanyServicesSoap)(this)).GetAllCompanyAsync(inValue);
        }
    }
}
