//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.UI.HRServiceNoticeInsertApp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notice", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Notice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuyuruAdiField;
        
        private System.DateTime DuyuruBaslamaTarihiField;
        
        private System.DateTime DuyuruBitisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuyuruAciklamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DuyuruAdi {
            get {
                return this.DuyuruAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.DuyuruAdiField, value) != true)) {
                    this.DuyuruAdiField = value;
                    this.RaisePropertyChanged("DuyuruAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DuyuruBaslamaTarihi {
            get {
                return this.DuyuruBaslamaTarihiField;
            }
            set {
                if ((this.DuyuruBaslamaTarihiField.Equals(value) != true)) {
                    this.DuyuruBaslamaTarihiField = value;
                    this.RaisePropertyChanged("DuyuruBaslamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DuyuruBitisTarihi {
            get {
                return this.DuyuruBitisTarihiField;
            }
            set {
                if ((this.DuyuruBitisTarihiField.Equals(value) != true)) {
                    this.DuyuruBitisTarihiField = value;
                    this.RaisePropertyChanged("DuyuruBitisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DuyuruAciklama {
            get {
                return this.DuyuruAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.DuyuruAciklamaField, value) != true)) {
                    this.DuyuruAciklamaField = value;
                    this.RaisePropertyChanged("DuyuruAciklama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HR.UI.HRServiceNoticeInsertApp.ResultOfListOfNotice))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfListOfNotice", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultOfListOfNotice : HR.UI.HRServiceNoticeInsertApp.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HR.UI.HRServiceNoticeInsertApp.Notice[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public HR.UI.HRServiceNoticeInsertApp.Notice[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HRServiceNoticeInsertApp.NoticeServicesSoap")]
    public interface NoticeServicesSoap {
        
        // CODEGEN: Generating message contract since element name notice from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        HR.UI.HRServiceNoticeInsertApp.InsertResponse Insert(HR.UI.HRServiceNoticeInsertApp.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.InsertResponse> InsertAsync(HR.UI.HRServiceNoticeInsertApp.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        HR.UI.HRServiceNoticeInsertApp.DeleteResponse Delete(HR.UI.HRServiceNoticeInsertApp.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.DeleteResponse> DeleteAsync(HR.UI.HRServiceNoticeInsertApp.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name notice from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        HR.UI.HRServiceNoticeInsertApp.UpdateResponse Update(HR.UI.HRServiceNoticeInsertApp.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.UpdateResponse> UpdateAsync(HR.UI.HRServiceNoticeInsertApp.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllNoticeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNotice", ReplyAction="*")]
        HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse GetAllNotice(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllNotice", ReplyAction="*")]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse> GetAllNoticeAsync(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(HR.UI.HRServiceNoticeInsertApp.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.Notice notice;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            this.notice = notice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(HR.UI.HRServiceNoticeInsertApp.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.Result InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(HR.UI.HRServiceNoticeInsertApp.Result InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(HR.UI.HRServiceNoticeInsertApp.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(HR.UI.HRServiceNoticeInsertApp.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.Result DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(HR.UI.HRServiceNoticeInsertApp.Result DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(HR.UI.HRServiceNoticeInsertApp.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.Notice notice;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            this.notice = notice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(HR.UI.HRServiceNoticeInsertApp.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.Result UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(HR.UI.HRServiceNoticeInsertApp.Result UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNoticeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNotice", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequestBody Body;
        
        public GetAllNoticeRequest() {
        }
        
        public GetAllNoticeRequest(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllNoticeRequestBody {
        
        public GetAllNoticeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllNoticeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllNoticeResponse", Namespace="http://tempuri.org/", Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponseBody Body;
        
        public GetAllNoticeResponse() {
        }
        
        public GetAllNoticeResponse(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllNoticeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HR.UI.HRServiceNoticeInsertApp.ResultOfListOfNotice GetAllNoticeResult;
        
        public GetAllNoticeResponseBody() {
        }
        
        public GetAllNoticeResponseBody(HR.UI.HRServiceNoticeInsertApp.ResultOfListOfNotice GetAllNoticeResult) {
            this.GetAllNoticeResult = GetAllNoticeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoticeServicesSoapChannel : HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoticeServicesSoapClient : System.ServiceModel.ClientBase<HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap>, HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap {
        
        public NoticeServicesSoapClient() {
        }
        
        public NoticeServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoticeServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticeServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoticeServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceNoticeInsertApp.InsertResponse HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.Insert(HR.UI.HRServiceNoticeInsertApp.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public HR.UI.HRServiceNoticeInsertApp.Result Insert(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            HR.UI.HRServiceNoticeInsertApp.InsertRequest inValue = new HR.UI.HRServiceNoticeInsertApp.InsertRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.InsertRequestBody();
            inValue.Body.notice = notice;
            HR.UI.HRServiceNoticeInsertApp.InsertResponse retVal = ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.InsertResponse> HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.InsertAsync(HR.UI.HRServiceNoticeInsertApp.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.InsertResponse> InsertAsync(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            HR.UI.HRServiceNoticeInsertApp.InsertRequest inValue = new HR.UI.HRServiceNoticeInsertApp.InsertRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.InsertRequestBody();
            inValue.Body.notice = notice;
            return ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceNoticeInsertApp.DeleteResponse HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.Delete(HR.UI.HRServiceNoticeInsertApp.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public HR.UI.HRServiceNoticeInsertApp.Result Delete(int id) {
            HR.UI.HRServiceNoticeInsertApp.DeleteRequest inValue = new HR.UI.HRServiceNoticeInsertApp.DeleteRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.DeleteRequestBody();
            inValue.Body.id = id;
            HR.UI.HRServiceNoticeInsertApp.DeleteResponse retVal = ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.DeleteResponse> HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.DeleteAsync(HR.UI.HRServiceNoticeInsertApp.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.DeleteResponse> DeleteAsync(int id) {
            HR.UI.HRServiceNoticeInsertApp.DeleteRequest inValue = new HR.UI.HRServiceNoticeInsertApp.DeleteRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.DeleteRequestBody();
            inValue.Body.id = id;
            return ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceNoticeInsertApp.UpdateResponse HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.Update(HR.UI.HRServiceNoticeInsertApp.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public HR.UI.HRServiceNoticeInsertApp.Result Update(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            HR.UI.HRServiceNoticeInsertApp.UpdateRequest inValue = new HR.UI.HRServiceNoticeInsertApp.UpdateRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.UpdateRequestBody();
            inValue.Body.notice = notice;
            HR.UI.HRServiceNoticeInsertApp.UpdateResponse retVal = ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.UpdateResponse> HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.UpdateAsync(HR.UI.HRServiceNoticeInsertApp.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.UpdateResponse> UpdateAsync(HR.UI.HRServiceNoticeInsertApp.Notice notice) {
            HR.UI.HRServiceNoticeInsertApp.UpdateRequest inValue = new HR.UI.HRServiceNoticeInsertApp.UpdateRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.UpdateRequestBody();
            inValue.Body.notice = notice;
            return ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.GetAllNotice(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest request) {
            return base.Channel.GetAllNotice(request);
        }
        
        public HR.UI.HRServiceNoticeInsertApp.ResultOfListOfNotice GetAllNotice() {
            HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest inValue = new HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequestBody();
            HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse retVal = ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).GetAllNotice(inValue);
            return retVal.Body.GetAllNoticeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse> HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap.GetAllNoticeAsync(HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest request) {
            return base.Channel.GetAllNoticeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HR.UI.HRServiceNoticeInsertApp.GetAllNoticeResponse> GetAllNoticeAsync() {
            HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest inValue = new HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequest();
            inValue.Body = new HR.UI.HRServiceNoticeInsertApp.GetAllNoticeRequestBody();
            return ((HR.UI.HRServiceNoticeInsertApp.NoticeServicesSoap)(this)).GetAllNoticeAsync(inValue);
        }
    }
}
